server:
  port: 7003

spring:
  application:
    name: springcloud-eureka
eureka:
  instance:
    hostname: eureka3  #eureka服务端的实例名称
  client:
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己
    fetch-registry: false  # 如果false 则表示自己为注册中心
    service-url: #监控页面
      defaultZone:  http://eureka1:7001/eureka,http://eureka2:7002/eureka

