server:
  port: 8080
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7001/eureka
    register-with-eureka: true
  instance:
    instance-id: springcloud-sonsumer-dept-8080
spring:
  application:
    name: springcloud-consumer-dept




